import { NextRequest, NextResponse } from "next/server";
import path from "path";
import fs from "fs";

/**
 * GET /api/metadata/[tokenId]
 * Returns ERC-721 metadata JSON for the given token ID.
 * The metadata files are pre-generated by scripts/generate-metadata.js
 * and served from the metadata/tokens/ directory at the repo root.
 */
export async function GET(
  _req: NextRequest,
  { params }: { params: { tokenId: string } }
) {
  const raw = params.tokenId.replace(/\.json$/i, "");
  const id  = parseInt(raw, 10);

  if (isNaN(id) || id < 1 || id > 40_000) {
    return NextResponse.json({ error: "Invalid token ID" }, { status: 400 });
  }

  // In production the metadata folder lives one level above the Next.js app.
  // Adjust the path if you move the metadata directory.
  const metaDir  = process.env.METADATA_DIR || path.join(process.cwd(), "..", "metadata", "tokens");
  const filePath = path.join(metaDir, `${id}.json`);

  if (!fs.existsSync(filePath)) {
    return NextResponse.json({ error: "Token metadata not found" }, { status: 404 });
  }

  const json = JSON.parse(fs.readFileSync(filePath, "utf-8"));
  return NextResponse.json(json, {
    headers: {
      "Cache-Control": "public, max-age=86400, immutable",
      "Content-Type":  "application/json",
    },
  });
}
